[33mWARNING [0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b51a87370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/277ba051fa7c8dd89988f37f39189026/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b51a87580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/277ba051fa7c8dd89988f37f39189026/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b51a87850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/277ba051fa7c8dd89988f37f39189026/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b51935eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/277ba051fa7c8dd89988f37f39189026
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b51935400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/277ba051fa7c8dd89988f37f39189026
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b51935340>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/277ba051fa7c8dd89988f37f39189026