{"uuid": "2de29a6c-7bbd-4881-8c9d-b23a5801d30e", "children": ["135f0a55-8edf-464c-9733-3f0a11171d7b", "395aa743-5792-4f9d-85b1-11cf0e5ed158", "9c39e686-dd28-4565-a280-48ca1fd92bc4", "b06dbe35-a840-4970-ac20-07b63ac33acc", "af351e51-0681-4fa2-bd5f-90cedef0ca00", "8ecbbfa1-687f-4bec-bc38-7c132d305ca4", "5e3b6d12-b567-4ba4-af5d-da3e4214cc0d", "92103753-09b0-41c3-ba7a-ab3b78c38ad2", "951f9013-b4b0-4520-8f4c-7f0bc0987e26", "83890d00-1e82-46f9-a776-07e680d6574e", "5929d548-0dda-425c-87f1-7e8f9832620f", "561b2f3e-ab19-4a57-950a-feaa021127e8", "978d96ce-b244-4a8c-b42e-9c28971ef5db", "680e2305-a2dd-4b6b-a0fb-37993b41889a", "e6e8c1cc-a13b-4251-8e0d-959d17b7b09a", "c6c67f8d-1486-4330-9e95-e4476ad91720", "79026684-b847-4497-9137-b3c98138c536", "cfee2d47-2ad8-4982-801b-68a796d9b37e"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=92.0.4515.159)\n\n", "trace": "  File \"/home/bipin/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/bipin/YIPL/Automation/PBMIS/testCases/conftest.py\", line 21, in setup\n    driver.set_window_position(0,0)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1131, in set_window_position\n    return self.set_window_rect(x=int(x), y=int(y))\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1180, in set_window_rect\n    return self.execute(Command.SET_WINDOW_RECT, {\"x\": x, \"y\": y,\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/bipin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1629275419162, "stop": 1629275420769}], "start": 1629275419162, "stop": 1629275421271}